services:
  app:
    image: ghcr.io/risc-v-kernelci-mentorship/riscv-lab:latest
    container_name: poll-builds
    environment:
      - EVENTS_STORAGE=/data/timestamp
      - LOGS_LOCATION=/data/riscv_lab.log
      - RISCV_ENV=prod
    restart: always
    volumes:
      - type: bind
        source: ${SECRETS_LOC} 
        target: /secrets.json
      - type: bind
        source: ${GITHUB_APP_CERT}
        target: /github_cert.pem
      - type: volume
        source: data 
        target: /data
volumes:
  data:
