services:
  app:
    image: ghcr.io/risc-v-kernelci-mentorship/riscv-lab:latest
    environment:
      - EVENTS_STORAGE=/data/timestamp
      - LOGS_LOCATION=/data/riscv_lab.log
    restart: always
    volumes:
      - type: bind
        source: ${SECRETS_LOC} 
        target: /secrets.json
      - type: volume
        source: data 
        target: /data
volumes:
  data:
