#!/usr/bin/perl

die "Usage: $0 FILE\n" if @ARGV < 1;
$filename = $ARGV[0];
my $tests_data;
{
	open my $fh, '<', $filename or die "Could not open file $filename: $!";
	local $/; # undefs $/ allowing us to read the whole file at once
	$tests_data = <$fh>;
}
$tests_data =~ s/(^breakpoints:.*\n)|(^net\/forwarding:.*\n)//mg; # with m the caret matches every start of line (not only the start of the file)
{
	open my $fh, '>', $filename or die "Could not open file $filename: $!";
	print $fh $tests_data;
}
