name: Submit to KCIDB

inputs:
  build-id:
    description: "KernelCI build id"
    required: true
    type: string
  logs-dir:
    description: "Path to the logs directory"
    required: true
    type: string
  kcidb-token:
    description: "Access token to KCIDB"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt update -y
        apt install -y --no-install-recommends python-dev-is-python3 pip virtualenv libpq-dev
        virtualenv -p python3 venv
        source venv/bin/activate
        pip install -r requirements.txt 
    - name: Run submit
      shell: bash
      env:
        KCIDB_TOKEN: ${{ inputs.kcidb-token }}
      run: |
        source venv/bin/activate
        cd riscvlab
        echo "$KCIDB_TOKEN" > kcidb.json
        export GOOGLE_APPLICATION_CREDENTIALS=kcidb.json
        python3 submit_results.py --build-id "${{ inputs.build-id }}" --logs-dir "${{ inputs.logs-dir }}" --submit-as-collections 

    
